-- =============================================================================
-- Seed: validated psychology instruments + library items
-- Source: supabase/seed/validated_scales.json
-- Regenerated by: scripts/generate_validated_scales_seed.py
-- =============================================================================

-- Ensure instruments tables exist (safe if schema already applied).
create table if not exists public.instruments (
  scale_id text primary key,
  name_kr text not null,
  name_en text not null,
  source text,
  response_scale jsonb not null,
  scoring_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.instrument_items (
  id uuid primary key default gen_random_uuid(),
  scale_id text not null references public.instruments (scale_id) on delete cascade,
  variable_name text not null,
  position_in_scale integer not null,
  subscale text,
  reverse_scored boolean not null default false,
  text_kr text not null,
  text_en text not null,
  created_at timestamptz not null default now(),
  constraint instrument_items_scale_variable_unique unique (scale_id, variable_name),
  constraint instrument_items_scale_position_unique unique (scale_id, position_in_scale)
);

-- Idempotent reload of library rows
delete from public.instrument_items where scale_id in (
  'dpes_awe', 'tipi', 'swls', 'prlq', 'spane', 'mvs', 'small_pes', 'awe_sf'
);
delete from public.instruments where scale_id in (
  'dpes_awe', 'tipi', 'swls', 'prlq', 'spane', 'mvs', 'small_pes', 'awe_sf'
);

-- ---- dpes_awe: Dispositional Positive Emotions Scale - Awe Subscale (DPES-Awe) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('dpes_awe', '기질적 긍정 정서 척도 - 경외감 하위척도', 'Dispositional Positive Emotions Scale - Awe Subscale (DPES-Awe)', 'Shiota, Keltner, & John (2006)', '{"type": "likert", "points": 7, "anchors_proposed_en": "1 = Strongly disagree ... 7 = Strongly agree", "verified": false}'::jsonb, 'No reverse-scored items in standard scoring (verify).');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('dpes_awe', 'dpes_awe_1', 1, NULL, false, '나는 종종 경이로움을 느낀다.', 'I often feel awe.'),
  ('dpes_awe', 'dpes_awe_2', 2, NULL, false, '나는 내 주변의 모든 것에서 아름다움을 느낀다.', 'I see beauty all around me.'),
  ('dpes_awe', 'dpes_awe_3', 3, NULL, false, '나는 거의 매일 경이로움을 느낀다.', 'I feel wonder almost every day.'),
  ('dpes_awe', 'dpes_awe_4', 4, NULL, false, '나는 종종 주변 사물들에서 패턴을 찾는다.', 'I often look for patterns in the objects around me.'),
  ('dpes_awe', 'dpes_awe_5', 5, NULL, false, '나는 자연의 아름다움을 볼 기회가 많다.', 'I have many opportunities to see the beauty of nature.'),
  ('dpes_awe', 'dpes_awe_6', 6, NULL, false, '나는 세상에 대한 이해의 지평을 넓힐 수 있는 경험들을 추구한다.', 'I seek out experiences that challenge my understanding of the world.');

-- ---- tipi: Ten-Item Personality Inventory (TIPI) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('tipi', '10문항 성격 검사', 'Ten-Item Personality Inventory (TIPI)', 'Gosling, Rentfrow, & Swann (2003)', '{"type": "likert", "points": 7, "anchors_proposed_en": "1 = Disagree strongly ... 7 = Agree strongly", "verified": false}'::jsonb, 'HIGH confidence. Reverse-scored: items 2,4,6,8,10. Dimensions (each = mean of one standard + one reverse item): Extraversion (1, 6R); Agreeableness (7, 2R); Conscientiousness (3, 8R); Emotional Stability (9, 4R); Openness (5, 10R).');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('tipi', 'tipi_1', 1, 'extraversion', false, '외향적이고, 적극적이다.', 'Extraverted, enthusiastic.'),
  ('tipi', 'tipi_2_r', 2, 'agreeableness', true, '비판적이고, 논쟁을 좋아한다.', 'Critical, quarrelsome.'),
  ('tipi', 'tipi_3', 3, 'conscientiousness', false, '믿음직스럽고, 자기 절제를 잘 한다.', 'Dependable, self-disciplined.'),
  ('tipi', 'tipi_4_r', 4, 'emotional_stability', true, '근심 걱정이 많고, 쉽게 흥분한다.', 'Anxious, easily upset.'),
  ('tipi', 'tipi_5', 5, 'openness', false, '새로운 경험에 개방적이고, 복잡다단하다.', 'Open to new experiences, complex.'),
  ('tipi', 'tipi_6_r', 6, 'extraversion', true, '내성적이고, 조용하다.', 'Reserved, quiet.'),
  ('tipi', 'tipi_7', 7, 'agreeableness', false, '동정심이 많고, 다정다감하다.', 'Sympathetic, warm.'),
  ('tipi', 'tipi_8_r', 8, 'conscientiousness', true, '정리정돈을 잘 못하고, 덤벙댄다.', 'Disorganized, careless.'),
  ('tipi', 'tipi_9', 9, 'emotional_stability', false, '차분하고, 감정의 기복이 적다.', 'Calm, emotionally stable.'),
  ('tipi', 'tipi_10_r', 10, 'openness', true, '변화를 싫어하고, 창의적이지 않다.', 'Conventional, uncreative.');

-- ---- swls: Satisfaction with Life Scale (SWLS) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('swls', '삶의 만족도 척도', 'Satisfaction with Life Scale (SWLS)', 'Diener, Emmons, Larsen, & Griffin (1985)', '{"type": "likert", "points": 7, "anchors_proposed_en": "1 = Strongly disagree ... 7 = Strongly agree", "verified": false}'::jsonb, 'HIGH confidence. No reverse-scored items. Total = sum of all 5.');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('swls', 'swls_1', 1, NULL, false, '전반적으로 볼때, 나의 삶은 나의 이상에 가깝다.', 'In most ways my life is close to my ideal.'),
  ('swls', 'swls_2', 2, NULL, false, '나의 삶의 상황들은 아주 좋다.', 'The conditions of my life are excellent.'),
  ('swls', 'swls_3', 3, NULL, false, '나는 나의 삶에 만족한다.', 'I am satisfied with my life.'),
  ('swls', 'swls_4', 4, NULL, false, '지금까지 내 삶에서 내가 원하는 중요한 것들을 이루어 냈다.', 'So far I have gotten the important things I want in life.'),
  ('swls', 'swls_5', 5, NULL, false, '만약 인생을 다시 산다 해도, 나는 거의 아무것도 바꾸지 않을 것이다.', 'If I could live my life over, I would change almost nothing.');

-- ---- prlq: Psychologically Rich Life Questionnaire (PRLQ) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('prlq', '심리적 풍요로운 삶 척도', 'Psychologically Rich Life Questionnaire (PRLQ)', 'Oishi et al. (2019)', '{"type": "likert", "points": 7, "anchors_proposed_en": "1 = Strongly disagree ... 7 = Strongly agree", "verified": false}'::jsonb, 'No reverse-scored items in standard scoring (verify).');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('prlq', 'prlq_1', 1, NULL, false, '내 삶은 지금까지 심리적으로 풍요로웠다.', 'My life has been psychologically rich.'),
  ('prlq', 'prlq_2', 2, NULL, false, '내 삶은 지금까지 경험적으로 풍요로웠다.', 'My life has been experientially rich.'),
  ('prlq', 'prlq_3', 3, NULL, false, '내 삶은 지금까지 감정적으로 풍요로웠다.', 'My life has been emotionally rich.'),
  ('prlq', 'prlq_4', 4, NULL, false, '나는 그동안 흥미로운 경험을 많이 해왔다.', 'I have had a lot of interesting experiences.'),
  ('prlq', 'prlq_5', 5, NULL, false, '나는 그동안 새로운 경험을 많이 해왔다.', 'I have had a lot of novel experiences.'),
  ('prlq', 'prlq_6', 6, NULL, false, '내 삶은 독특하고 흔치 않은 경험들로 가득하다.', 'My life has been full of unique, unusual experiences.'),
  ('prlq', 'prlq_7', 7, NULL, false, '내 삶은 다채롭고 강렬한 순간들로 이뤄져 있다.', 'My life consists of rich, intense moments.'),
  ('prlq', 'prlq_8', 8, NULL, false, '나는 여행이나 콘서트와 같은 직접 경험을 통해 폭넓은 감정을 경험한다.', 'I experience a full range of emotions via first-hand experiences such as travel and attending concerts.'),
  ('prlq', 'prlq_9', 9, NULL, false, '나는 다른 사람들에게 이야기할 개인적인 이야기들이 많다.', 'I have a lot of personal stories to tell others.'),
  ('prlq', 'prlq_10', 10, NULL, false, '나는 죽기 직전에, "나는 재미있는 인생을 살았다"라고 말할 것 같다.', 'On my deathbed, I am likely to say "I had an interesting life".'),
  ('prlq', 'prlq_11', 11, NULL, false, '나는 죽기 직전에, "나는 많은 것을 보고 배웠다"라고 말할 것 같다.', 'On my deathbed, I am likely to say "I have seen and learned a lot".'),
  ('prlq', 'prlq_12', 12, NULL, false, '내 삶은 좋은 소설이나 영화로 만들 만하다.', 'My life would make a good novel or movie.');

-- ---- spane: Scale of Positive and Negative Experience (SPANE) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('spane', '긍정 및 부정 경험 척도', 'Scale of Positive and Negative Experience (SPANE)', 'Diener et al. (2010)', '{"type": "likert", "points": 5, "anchors_proposed_en": "1 = Very rarely or never ... 5 = Very often or always", "verified": false}'::jsonb, 'HIGH confidence. Not reverse-scored; two subscales. SPANE-P = sum of positive items (1,3,4,5,6,7); SPANE-N = sum of negative items (2,8,9,10,11,12); SPANE-B (balance) = P - N.');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('spane', 'spane_pos_1', 1, 'positive', false, '긍정적인', 'Positive'),
  ('spane', 'spane_neg_1', 2, 'negative', false, '부정적인', 'Negative'),
  ('spane', 'spane_pos_2', 3, 'positive', false, '좋은', 'Good'),
  ('spane', 'spane_pos_3', 4, 'positive', false, '유쾌한', 'Pleasant'),
  ('spane', 'spane_pos_4', 5, 'positive', false, '행복한', 'Happy'),
  ('spane', 'spane_pos_5', 6, 'positive', false, '즐거운', 'Joyful'),
  ('spane', 'spane_pos_6', 7, 'positive', false, '만족한', 'Contented'),
  ('spane', 'spane_neg_2', 8, 'negative', false, '나쁜', 'Bad'),
  ('spane', 'spane_neg_3', 9, 'negative', false, '불쾌한', 'Unpleasant'),
  ('spane', 'spane_neg_4', 10, 'negative', false, '슬픈', 'Sad'),
  ('spane', 'spane_neg_5', 11, 'negative', false, '두려운', 'Afraid'),
  ('spane', 'spane_neg_6', 12, 'negative', false, '화난', 'Angry');

-- ---- mvs: Material Values Scale - Short Form (MVS) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('mvs', '물질주의 가치 척도 (축약본)', 'Material Values Scale - Short Form (MVS)', 'Richins (2004); original: Richins & Dawson (1992)', '{"type": "likert", "points": 5, "anchors_proposed_en": "1 = Strongly disagree ... 5 = Strongly agree", "verified": false}'::jsonb, 'VERIFY — reverse-scoring NOT confirmed for this 18-item variant. Subscales: Success (SS), Centrality (C), Happiness (H). Items expressing LOW materialism are conventionally reverse-coded; the reverse_scored flags below are my best inference from item direction and MUST be checked against Richins'' scoring key before use.');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('mvs', 'mvs_ss_1', 1, 'success', false, '나는 고가의 집, 차, 옷을 가진 사람들이 존경스럽고 부럽다.', 'I admire people who own expensive homes, cars, and clothes.'),
  ('mvs', 'mvs_ss_2', 2, 'success', false, '물질적으로 풍족해지는 것이 내 인생에 있어서 가장 중요한 성취 중 하나이다.', 'Some of the most important achievements in life include acquiring material possessions.'),
  ('mvs', 'mvs_ss_3_r', 3, 'success', true, '사람들이 소유한 물질의 양이 인생에서의 가장 중요한 성공의 지표는 아니다.', 'I don''t place much emphasis on the amount of material objects people own as a sign of success.'),
  ('mvs', 'mvs_ss_4', 4, 'success', false, '내가 소유한 것들은 내가 얼마나 인생을 성공적으로 살아가고 있는지 보여준다.', 'The things I own say a lot about how well I''m doing in life.'),
  ('mvs', 'mvs_ss_5', 5, 'success', false, '나는 사람들이 부러워할 만한 것들을 갖고 있는 게 좋다.', 'I like to own things that impress people.'),
  ('mvs', 'mvs_ss_6_r', 6, 'success', true, '나는 타인의 물질적 소유물에 별 관심이 없다.', 'I don''t pay much attention to the material objects other people own.'),
  ('mvs', 'mvs_c_1_r', 7, 'centrality', true, '나는 대개 내가 필요한 물건만 산다.', 'I usually buy only the things I need.'),
  ('mvs', 'mvs_c_2_r', 8, 'centrality', true, '나는 많은 것을 소유하지 않는 소박한 삶을 살려고 노력한다.', 'I try to keep my life simple, as far as possessions are concerned.'),
  ('mvs', 'mvs_c_3_r', 9, 'centrality', true, '내가 무엇을 소유하고 있는지는 별로 중요하지 않다.', 'The things I own aren''t all that important to me.'),
  ('mvs', 'mvs_c_4', 10, 'centrality', false, '나는 실용적이지 않은 물건을 사는 것을 좋아한다.', 'I enjoy spending money on things that aren''t practical.'),
  ('mvs', 'mvs_c_5', 11, 'centrality', false, '쇼핑은 내게 큰 기쁨을 준다.', 'Buying things gives me a lot of pleasure.'),
  ('mvs', 'mvs_c_6', 12, 'centrality', false, '나는 럭셔리한(호화로운) 삶이 좋다.', 'I like a lot of luxury in my life.'),
  ('mvs', 'mvs_c_7_r', 13, 'centrality', true, '나는 내 주변 사람들에 비해 물질적 소유물을 덜 중요하게 여긴다.', 'I put less emphasis on material things than most people I know.'),
  ('mvs', 'mvs_h_1_r', 14, 'happiness', true, '나는 인생을 즐겁게 사는 데 꼭 필요한 모든 것들을 갖고 있다.', 'I have all the things I really need to enjoy life.'),
  ('mvs', 'mvs_h_2', 15, 'happiness', false, '내가 갖고 있지 않은 어떤 물건을 소유하게 되면 내 삶은 더 나아질 것이다.', 'My life would be better if I owned certain things I don''t have.'),
  ('mvs', 'mvs_h_3_r', 16, 'happiness', true, '더 비싸고 좋은 물건들을 소유한다고 해서 내가 더 행복해지는 것은 아니다.', 'I wouldn''t be any happier if I owned nicer things.'),
  ('mvs', 'mvs_h_4', 17, 'happiness', false, '더 많은 것들을 구매할 수 있는 경제적 여유가 주어진다면 나는 더 행복해질 것이다.', 'I''d be happier if I could afford to buy more things.'),
  ('mvs', 'mvs_h_5', 18, 'happiness', false, '내가 갖고 싶은 모든 것들을 살 수 있는 경제적 여유가 없다는 것 때문에 매우 속상하다.', 'It sometimes bothers me quite a bit that I can''t afford to buy all the things I''d like.');

-- ---- small_pes: Small Self + Psychological Entitlement Scale (Small_PES) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('small_pes', '작은 자아 및 심리적 특권 의식 척도', 'Small Self + Psychological Entitlement Scale (Small_PES)', 'Small Self: Piff et al. (2015) / Shiota et al. (2007); PES: Campbell et al. (2004)', '{"type": "likert", "points": 7, "anchors_proposed_en": "1 = Strongly disagree ... 7 = Strongly agree", "verified": false}'::jsonb, 'This is TWO instruments combined. Score Small Self (items 1-2) and PES (items 3-11) as SEPARATE variables — do NOT sum together. PES has one reverse item (''I do not necessarily deserve special treatment'') = pes_5_r (HIGH confidence). Confirm Small Self scoring direction against its source.');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('small_pes', 'smallself_1', 1, 'small_self', false, '나는 대체로 내 자신이 초라하게 느껴진다.', 'In general, I feel relatively small.'),
  ('small_pes', 'smallself_2', 2, 'small_self', false, '나는 대체로 내 자신이 보잘것없는 존재라고 느낀다.', 'In general, I feel insignificant.'),
  ('small_pes', 'pes_1', 3, 'entitlement', false, '나는 솔직히 다른 사람들보다 더 많은 것을 누릴 자격이 있다고 느낀다.', 'I honestly feel I am just more deserving than others.'),
  ('small_pes', 'pes_2', 4, 'entitlement', false, '중요한 일들은 나에게 주어져야 한다.', 'Great things should come to me.'),
  ('small_pes', 'pes_3', 5, 'entitlement', false, '위급한 상황에서 내가 가장 먼저 구조될 자격이 있다.', 'If I were on the Titanic, I would deserve to be on the first lifeboat!'),
  ('small_pes', 'pes_4', 6, 'entitlement', false, '나는 그럴 만한 가치가 있기에 최고를 요구한다.', 'I demand the best because I am worth it.'),
  ('small_pes', 'pes_5_r', 7, 'entitlement', true, '내가 꼭 특별 대우를 받을 자격이 있는 것은 아니다.', 'I do not necessarily deserve special treatment.'),
  ('small_pes', 'pes_6', 8, 'entitlement', false, '나는 내 인생에서 더 많은 것들을 누릴 자격이 있다.', 'I deserve more things in my life.'),
  ('small_pes', 'pes_7', 9, 'entitlement', false, '나와 같은 사람들은 때때로 더 많은 휴식을 누릴 자격이 있다.', 'People like me deserve an extra break now and then.'),
  ('small_pes', 'pes_8', 10, 'entitlement', false, '모든 일이 내가 원하는 대로 되어야 한다.', 'Things should go my way.'),
  ('small_pes', 'pes_9', 11, 'entitlement', false, '나는 모든 것을 더 많이 누릴 자격이 있다고 느낀다.', 'I feel entitled to more of everything.');

-- ---- awe_sf: Awe Experience Scale - Short Form (AWE-SF) ----
insert into public.instruments (scale_id, name_kr, name_en, source, response_scale, scoring_note) values ('awe_sf', '짧은 형태의 경외감 경험 척도', 'Awe Experience Scale - Short Form (AWE-SF)', 'Yaden et al. (2019)', '{"type": "likert", "points": 7, "anchors_proposed_en": "1 = Strongly disagree ... 7 = Strongly agree", "verified": false}'::jsonb, 'No reverse-scored items (verify). Six two-item factors: time perception (1,2), self-diminishment (3,4), connectedness (5,6), vastness (7,8), physical sensations (9,10), need for accommodation (11,12).');
insert into public.instrument_items (scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values
  ('awe_sf', 'awe_sf_1', 1, 'time_perception', false, '나는 순간 주변의 모든 것이 느려지는 느낌을 받았다.', 'I sensed things momentarily slow down.'),
  ('awe_sf', 'awe_sf_2', 2, 'time_perception', false, '나는 시간이 천천히 흐르는 것처럼 느꼈다.', 'I noticed time slowing.'),
  ('awe_sf', 'awe_sf_3', 3, 'self_diminishment', false, '내 존재가 작아진 느낌이 들었다.', 'I felt my sense of self was diminished.'),
  ('awe_sf', 'awe_sf_4', 4, 'self_diminishment', false, '내 자신이 위축된 것을 느꼈다.', 'I felt my sense of self shrink.'),
  ('awe_sf', 'awe_sf_5', 5, 'connectedness', false, '나는 모든 것과 연결되어 있다는 느낌을 받았다.', 'I had the sense of being connected to everything.'),
  ('awe_sf', 'awe_sf_6', 6, 'connectedness', false, '나는 모든 살아있는 것들과 교감하는 느낌을 받았다.', 'I felt a sense of communion with all living things.'),
  ('awe_sf', 'awe_sf_7', 7, 'vastness', false, '나는 어떤 거대한 존재와 함께 있다고 느꼈다.', 'I felt that I was in the presence of something grand.'),
  ('awe_sf', 'awe_sf_8', 8, 'vastness', false, '나 보다 더 큰 무언가를 경험했다.', 'I experienced something greater than myself.'),
  ('awe_sf', 'awe_sf_9', 9, 'physical_sensations', false, '나는 놀라서 입이 떡 벌어졌다.', 'I felt my jaw drop.'),
  ('awe_sf', 'awe_sf_10', 10, 'physical_sensations', false, '나는 소름이 돋았다.', 'I had goosebumps.'),
  ('awe_sf', 'awe_sf_11', 11, 'need_for_accommodation', false, '내가 경험한 것을 이해하고 받아들이기가 쉽지 않았다.', 'I felt challenged to mentally process what I was experiencing.'),
  ('awe_sf', 'awe_sf_12', 12, 'need_for_accommodation', false, '나는 그 경험을 완전히 이해하는 것이 힘들었다.', 'I found it hard to comprehend the experience in full.');

-- =============================================================================
-- Mapping note (application copies library → survey_items on pick):
--   instrument_items.variable_name      → survey_items.variable_name
--   instrument_items.position_in_scale  → survey_items.position_in_scale
--   instrument_items.subscale           → survey_items.subscale
--   instrument_items.reverse_scored     → survey_items.reverse_scored
--   instrument_items.text_kr            → survey_items.item_text_kr (+ item_text default)
--   instrument_items.text_en            → survey_items.item_text_en
--   instruments.scale_id / name_*       → survey_items.source_scale_id / scale_name
--   instruments.response_scale          → survey_items.response_options / anchors
-- =============================================================================
