#!/usr/bin/env python3
"""Regenerate supabase/seed/validated_scales_seed.sql from validated_scales.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "supabase" / "seed" / "validated_scales.json"
OUT_PATH = ROOT / "supabase" / "seed" / "validated_scales_seed.sql"


def esc(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def esc_json(obj: object) -> str:
    return "'" + json.dumps(obj, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def main() -> None:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    scales = data["scales"]
    lines: list[str] = [
        "-- =============================================================================",
        "-- Seed: validated psychology instruments + library items",
        "-- Source: supabase/seed/validated_scales.json",
        "-- Regenerated by: scripts/generate_validated_scales_seed.py",
        "-- =============================================================================",
        "",
        "create table if not exists public.instruments (",
        "  scale_id text primary key,",
        "  name_kr text not null,",
        "  name_en text not null,",
        "  source text,",
        "  response_scale jsonb not null,",
        "  scoring_note text,",
        "  created_at timestamptz not null default now()",
        ");",
        "",
        "create table if not exists public.instrument_items (",
        "  id uuid primary key default gen_random_uuid(),",
        "  scale_id text not null references public.instruments (scale_id) on delete cascade,",
        "  variable_name text not null,",
        "  position_in_scale integer not null,",
        "  subscale text,",
        "  reverse_scored boolean not null default false,",
        "  text_kr text not null,",
        "  text_en text not null,",
        "  created_at timestamptz not null default now(),",
        "  constraint instrument_items_scale_variable_unique unique (scale_id, variable_name),",
        "  constraint instrument_items_scale_position_unique unique (scale_id, position_in_scale)",
        ");",
        "",
        "delete from public.instrument_items where scale_id in (",
        "  " + ", ".join(esc(s["scale_id"]) for s in scales),
        ");",
        "delete from public.instruments where scale_id in (",
        "  " + ", ".join(esc(s["scale_id"]) for s in scales),
        ");",
        "",
    ]

    for s in scales:
        lines.append(f"-- ---- {s['scale_id']}: {s['name_en']} ----")
        lines.append(
            "insert into public.instruments "
            "(scale_id, name_kr, name_en, source, response_scale, scoring_note) values ("
            f"{esc(s['scale_id'])}, {esc(s['name_kr'])}, {esc(s['name_en'])}, "
            f"{esc(s['source'])}, {esc_json(s['response_scale'])}, {esc(s['scoring_note'])}"
            ");"
        )
        lines.append(
            "insert into public.instrument_items "
            "(scale_id, variable_name, position_in_scale, subscale, reverse_scored, text_kr, text_en) values"
        )
        vals = []
        for it in s["items"]:
            sub = esc(it["subscale"]) if it["subscale"] is not None else "NULL"
            vals.append(
                f"  ({esc(s['scale_id'])}, {esc(it['variable_name'])}, {it['position_in_scale']}, "
                f"{sub}, {'true' if it['reverse_scored'] else 'false'}, "
                f"{esc(it['text_kr'])}, {esc(it['text_en'])})"
            )
        lines.append(",\n".join(vals) + ";")
        lines.append("")

    lines.extend(
        [
            "-- Library → survey_items mapping (app copies on researcher pick):",
            "--   variable_name, position_in_scale, subscale, reverse_scored,",
            "--   text_kr → item_text_kr (+ item_text default), text_en → item_text_en,",
            "--   scale_id → source_scale_id, name_* → scale_name, response_scale → options.",
            "",
        ]
    )
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(scales)} scales)")


if __name__ == "__main__":
    main()
